on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
      - name: zip code
        run: |
          mkdir EzArduino 
          mv *.h EzArduino
          zip -r EzArduino.zip EzArduino
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: EzArduino.zip
          token: ${{secrets.GH_ACCESS_TOKEN}}
