on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: EzArduino
          path: ./*.h
      - name: Download artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: EzArduino
          path: ./
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./EzArduino.zip
